#!/bin/bash
echo "=> Building Environmental Variables..."

echo "=> Building with REACT_APP_AMAZON_MUSIC_BASE_URL $REACT_APP_AMAZON_MUSIC_BASE_URL"
echo "=> Building with REACT_APP_AMAZON_API_BASE_URL $REACT_APP_AMAZON_API_BASE_URL"

docker build \
--build-arg REACT_APP_AMAZON_MUSIC_BASE_URL=${REACT_APP_AMAZON_MUSIC_BASE_URL} \
--build-arg REACT_APP_AMAZON_API_BASE_URL=${REACT_APP_AMAZON_API_BASE_URL}  \
. -t $IMAGE_NAME

if [ -e .env ]; then
    echo ".env file already exists"
else
    echo "REACT_APP_AMAZON_MUSIC_BASE_URL=$REACT_APP_AMAZON_MUSIC_BASE_URL" > .env
    echo "REACT_APP_AMAZON_API_BASE_URL=$REACT_APP_AMAZON_API_BASE_URL" >> .env
fi
echo "SKIP_PREFLIGHT_CHECK=true" >> .env

echo "=> Finished Building Environmental Variables!"